### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by masato-teshita** [masato-teshita/freemarket_sample_68d#160]
■ URL
IPアドレス：https://www.furima-68d.work/
Github（最終課題のリポジトリ）：https://github.com/masato-teshita/freemarket_sample_68d

■ Basic認証
ID：admin
Pass：68d68d

■ テスト用アカウント
◯ 購入者用
メールアドレス：buy_user@furima.work
パスワード：1111aaa

◯ 購入用カード情報
番号：4242424242424242
期限：2022/01
セキュリティコード：123

◯ 出品者用
メールアドレス：sell_user@furima.work
パスワード：2222bbb

**Comment by MakiTaka** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
❶ログインしていないと商品詳細が見れない
[![Image from Gyazo](https://i.gyazo.com/5fa74d66e9b77e72880b8ff9132fe16e.png)](https://gyazo.com/5fa74d66e9b77e72880b8ff9132fe16e)

❷出品内容・販売価格が企業様から見た場合、適切とは言い難いものになっています。
※著作権に反する画像は使用していませんでしょうか？（フリー素材などであれば大丈夫でしょうが、ネットからそのまま引用していませんか？）
※販売価格に関して、あきらかに法外な数値になっていると見本とはいえ、企業様から見てもいい印象はございません。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by masato-teshita** [comment]
@MakiTaka 
ご指摘いただきありがとうございます。修正して再度提出いたします。

**Comment by MakiTaka** [comment]
> 著作出品内容・販売価格が企業様から見た場合、適切とは言い難いものになっています。
こちら細かいことかもしれませんが、昨今コンプライアンスが厳しい環境になっております。
企業としてもそれを遵守できる人材でないと会社の経営を大きく傾ける要因になってしまうこともありますので、ご対応のほどよろしくお願いいたします。

**Comment by masato-teshita** [comment]
@MakiTaka 
了解しました。テストで出品されているSurfaceはセーフと考えていいんでしょうか？

**Comment by MakiTaka** [comment]
Surfaceの画像をどこから取得したかによります。
ご自身で撮った写真であったり、フリー素材や購入した画像などで、正規のルートで取得したのであれば権利関係を主張されることはありませんが、ネットの画像検索で引っ張ってきたよくわからないものはアウトになる可能性が高いです。

LGTMをだす分にはそこまで厳密には見ませんが、転職をされる方はこちらのウェブアプリケーションは企業に提出します。
明日までに修正が難しいようであれば後日でも構わないので、修正していただいておいたほうが無難です。
（例えばパソコンのフリー素材の画像にするとか）

**Comment by masato-teshita** [comment]
@MakiTaka 
ご丁寧にありがとうございます。
万事を期すために、画像は全てフリー素材のサイトから取得しようと思います。

**Comment by MakiTaka** [comment]
発表会間近のタイミングにてお手数おかけしますが、ご対応のほどよろしくお願いします。

**Comment by iwataayumu** [comment]
masato-teshitaさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
発表会間近の修正となり、お手数おかけしましたが迅速な対応ありがとうございました！

※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。
